version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./apps/api/secrets:/app/apps/api/secrets:ro
    networks:
      - app-network

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge